### ISSUE TITLE
Just a Question really 

### ISSUE THREAD

**Issue by lrarbin** [jsanjose/zxbasic-vscode#1]
I was wondering how difficult it would be to add in support for Intellisense / Definitions etc?
ZX Basic doesn't have that many command, so it would be good to have descriptions etc.

Laurence

**Comment by jsanjose** [comment]
It's not so difficult. As you as noted ZX Basic as not many commands, and it has a simple syntax. The fact is that I have no time now. Whenever I've time I will look to add Intellisense support.

**Comment by boriel** [comment]
I'm (sort of) working on it. The idea is to support LSP ([Language Server Protocol](https://github.com/Microsoft/language-server-protocol)) which is supported by VSCode, Sublime, Atom and many other (even vim is going to adopt it).
The problem is I lack a lot of info in how to implement this, so any help would be appreciated.

**Comment by jsanjose** [comment]
I don't have many information about LSP. I've been trying to learn about it myself, but due to the lack of I had to leave it for later.
